# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
permalink:           pretty

# Setup
title:               MarthLab
tagline:             'real-time genomic analysis'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://marthlab.github
baseurl:             

#Collections
collections:
 - members
 - tools
 - publications

# About/contact
author:
  name:              Chase Miller
  url:               https://twitter.com/ChaseAllnMiller
  email:             chmille4@gmail.com

# Custom vars
version:             1.0.0

exclude: [bin]
